# Generated by Django 5.1 on 2024-10-01 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="blog_images/")),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Technology", "Technology"),
                            ("Fashion", "Fashion"),
                            ("Travel", "Travel"),
                            ("LifeStyle", "LifeStyle"),
                            ("Sports", "Sports"),
                            ("Finance", "Finance"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
